import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { createServer, type Server } from 'node:http';
import { once } from 'node:events';
import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { setTimeout as delay } from 'node:timers/promises';
import type { AddressInfo } from 'node:net';
import { createSession } from '../../apps/server/auth.ts';
import { createStudioServer } from '../../apps/server/http.ts';
import { engineFixture } from '../server/helpers/engine-fixture.ts';
import { openBrowser } from './helpers.ts';

const root = fileURLToPath(new URL('../../', import.meta.url));
const studio = join(root, 'apps/studio');
const close = (server: Server) => new Promise<void>(resolve => { server.closeAllConnections(); server.close(() => resolve()); });
async function freePort() { const server = createServer(); server.listen(0, '127.0.0.1'); await once(server, 'listening'); const port = (server.address() as AddressInfo).port; await close(server); return port; }

test('API access creates scoped expiring keys, supplies connection examples and clears one-time secrets', { timeout: 90000 }, async t => {
  const fixture = await engineFixture();
  const port = await freePort(), origin = `http://127.0.0.1:${port}`;
  const server = await createStudioServer({ store: fixture.store, engine: fixture.engine, allowedOrigins: [origin], setupSecret: 'api-access-browser-fixture' });
  server.listen(0, '127.0.0.1'); await once(server, 'listening');
  const backend = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  await fixture.engine.start();
  let logs = '';
  const child = spawn(process.execPath, [join(studio, 'node_modules/next/dist/bin/next'), 'start', '--hostname', '127.0.0.1', '--port', String(port)], { cwd: studio, env: { ...process.env, GRAVITY_SERVER_URL: backend }, stdio: ['ignore', 'pipe', 'pipe'] });
  child.stdout.on('data', chunk => { logs = (logs + chunk.toString()).slice(-4000); }); child.stderr.on('data', chunk => { logs = (logs + chunk.toString()).slice(-4000); });
  t.after(async () => { child.kill('SIGTERM'); await delay(200); if (child.exitCode === null) child.kill('SIGKILL'); await server.closeOperations(); await close(server); await fixture.close(); });
  for (let attempt = 0; attempt < 100; attempt++) { try { if ((await fetch(`${origin}/api/health`)).ok) break; } catch { /* Starting. */ } if (child.exitCode !== null || attempt === 99) throw new Error(`API access frontend could not start: ${logs}`); await delay(100); }
  const cookie = createSession(fixture.store, fixture.owner, false).split(';')[0];
  const browser = await openBrowser(t);
  await browser.send('Network.setCookie', { name: cookie.split('=')[0], value: cookie.split('=')[1], url: origin, httpOnly: true, sameSite: 'Strict' });
  await browser.navigate(`${origin}/image`);
  await browser.until('!!document.querySelector("#image-prompt") && !document.querySelector("dialog[open]")', 'The isolated workspace opens');
  await browser.click('header button[aria-label="Settings"]');
  await browser.click('#settings-tab-api');
  await browser.until("!!document.querySelector('select[aria-label=\"Token permissions\"]')", 'Scoped API access controls load');
  assert.equal(await browser.evaluate("document.querySelector('input[aria-label=\"MCP server address\"]').value"), `${origin}/api/mcp`);
  assert.equal(await browser.evaluate("document.querySelector('input[aria-label=\"OpenAI-compatible base URL\"]').value"), `${origin}/v1`);
  await browser.click('#settings-panel-api details > summary');
  const config = await browser.evaluate<string>("document.querySelector('#settings-panel-api pre').textContent");
  assert.deepEqual(JSON.parse(config), { mcpServers: { 'gravity-studio': { type: 'http', url: `${origin}/api/mcp`, headers: { Authorization: 'Bearer YOUR_TOKEN' } } } });
  await browser.clickText('Image API');
  assert.match(await browser.evaluate<string>("document.querySelector('#settings-panel-api pre').textContent"), /\/v1\/images\/generations/);
  assert.match(await browser.evaluate<string>("document.querySelector('#settings-panel-api pre').textContent"), /\$GRAVITY_API_KEY/);
  await browser.clickText('Edit image');
  assert.match(await browser.evaluate<string>("document.querySelector('#settings-panel-api pre').textContent"), /\/v1\/images\/edits/);
  assert.match(await browser.evaluate<string>("document.querySelector('#settings-panel-api pre').textContent"), /image=@reference\.png/);
  await browser.clickText('Chat API');
  assert.match(await browser.evaluate<string>("document.querySelector('#settings-panel-api pre').textContent"), /\/v1\/chat\/completions/);
  await browser.fill('input[placeholder="My MCP client"]', 'Read-only browser client');
  await browser.fill('select[aria-label="Token permissions"]', 'read');
  await browser.click('#settings-panel-api form details > summary');
  assert.equal(await browser.evaluate("document.querySelectorAll('#settings-panel-api form input[type=checkbox]:checked').length"), 3);
  await browser.click('#settings-panel-api form input[type=checkbox]');
  assert.equal(await browser.evaluate("document.querySelector('select[aria-label=\"Token permissions\"]').value"), 'custom', 'Changing an individual permission leaves the preset');
  await browser.click('#settings-panel-api form input[type=checkbox]');
  await browser.fill('select[aria-label="Token expiration"]', '7');
  await browser.clickText('Create token');
  await browser.until("document.querySelector('input[aria-label=\"New access token\"]')?.value.startsWith('gs_')", 'The token is displayed once');
  const token = await browser.evaluate<string>("document.querySelector('input[aria-label=\"New access token\"]').value");
  const list = await (await fetch(`${origin}/api/tokens`, { headers: { Cookie: cookie } })).json() as { tokens: Array<{ id: string; scopes: string[]; expiresAt: string; lastUsedAt: string | null }> };
  assert.deepEqual([...list.tokens[0].scopes].sort(), ['assets:read', 'jobs:read', 'models:read']);
  const remaining = Date.parse(list.tokens[0].expiresAt) - Date.now();
  assert(remaining > 6.99 * 86400000 && remaining <= 7 * 86400000, 'The browser selection is enforced by the real server');
  assert.equal('token' in list.tokens[0], false);
  const catalogResponse = await fetch(`${origin}/api/catalog`, { headers: { Authorization: `Bearer ${token}` } });
  assert.equal(catalogResponse.status, 200);
  const catalog = await catalogResponse.json() as { models: Array<{ id: string; ready: boolean }> };
  for (const path of ['/v1/models', '/api/v1/models']) {
    const response = await fetch(`${origin}${path}`, { headers: { Authorization: `Bearer ${token}` } });
    assert.equal(response.status, 200, `${path} forwards the token through the frontend`);
    assert.match(response.headers.get('x-request-id') ?? '', /^[a-f0-9-]{36}$/);
    const models = await response.json() as { object: string; data: Array<{ id: string; type: string; ready: boolean }> };
    assert.equal(models.object, 'list');
    assert.deepEqual(models.data.filter(model => model.type === 'image').map(({ id, ready }) => ({ id, ready })), catalog.models.map(({ id, ready }) => ({ id, ready })));
    const rejected = await fetch(`${origin}${path}`);
    assert.equal(rejected.status, 401);
    const failure = await rejected.json();
    assert.equal(failure.error.type, 'authentication_error'); assert.equal(failure.error.param, null);
    assert.equal(typeof failure.error.message, 'string'); assert.equal(typeof failure.error.code, 'string');
    assert.equal(rejected.headers.get('x-request-id'), failure.requestId, 'OpenAI failures preserve their request ID');
  }
  const mcpHeaders = { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', Accept: 'application/json, text/event-stream' };
  const mcpJson = async (response: Response) => { const body = await response.text(); return JSON.parse(response.headers.get('content-type')?.includes('text/event-stream') ? body.split('\n').find(line => line.startsWith('data: '))!.slice(6) : body); };
  const initialized = await fetch(`${origin}/api/mcp`, { method: 'POST', headers: { ...mcpHeaders, 'MCP-Protocol-Version': '2025-11-25' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-11-25', capabilities: {}, clientInfo: { name: 'browser-access', version: '1' } } }) });
  assert.equal(initialized.status, 200); assert.equal((await mcpJson(initialized)).result.serverInfo.name, 'gravity-studio');
  const tools = await fetch(`${origin}/api/mcp`, { method: 'POST', headers: { ...mcpHeaders, 'MCP-Protocol-Version': '2026-07-28', 'Mcp-Method': 'tools/list' }, body: JSON.stringify({ jsonrpc: '2.0', id: 2, method: 'tools/list', params: { _meta: { 'io.modelcontextprotocol/protocolVersion': '2026-07-28', 'io.modelcontextprotocol/clientInfo': { name: 'browser-access', version: '1' }, 'io.modelcontextprotocol/clientCapabilities': {} } } }) });
  assert.equal(tools.status, 200, 'Current MCP transport headers survive the frontend proxy');
  const names = (await mcpJson(tools)).result.tools.map((tool: { name: string }) => tool.name);
  assert(names.includes('gravity_models_list')); assert(names.includes('gravity_jobs_list'));
  assert.equal(names.includes('gravity_job_submit'), false, 'Read-only keys expose no generation tool');
  assert.equal((await fetch(`${origin}/api/jobs`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ modelId: 'sdxl-base', prompt: 'This read-only client must not enqueue work.' }) })).status, 403);
  assert.equal(fixture.store.jobs().length, 0);
  assert.equal(await browser.evaluate(`Object.values(localStorage).some(value => value.includes(${JSON.stringify(token)})) || Object.values(sessionStorage).some(value => value.includes(${JSON.stringify(token)}))`), false, 'Plaintext keys are not saved to browser storage');
  assert.equal(await browser.evaluate(`document.querySelector('#settings-panel-api pre').textContent.includes(${JSON.stringify(token)})`), false, 'Copied configurations never embed the visible key');
  await browser.click('button[aria-label="Close settings"]');
  await browser.click('header button[aria-label="Settings"]');
  await browser.until("!!document.querySelector('#settings-dialog[open] #settings-panel-api')", 'The API panel reopens');
  assert.equal(await browser.evaluate("!!document.querySelector('input[aria-label=\"New access token\"]')"), false, 'Closing clears the one-time plaintext');
  await browser.click('#settings-tab-app'); await browser.click('#settings-tab-api');
  await browser.until("document.querySelector('#settings-panel-api')?.innerText.includes('Last used')", 'Token usage is visible after refresh');
  const screenshots = join(root, '.local/screenshots'); await mkdir(screenshots, { recursive: true });
  await browser.screenshot(join(screenshots, 'api-access-desktop.png'));
  await browser.click('#settings-panel-api details > summary');
  await browser.clickText('Image API');
  for (const width of [390, 320]) {
    await browser.send('Emulation.setDeviceMetricsOverride', { width, height: 844, deviceScaleFactor: 1, mobile: true });
    await browser.evaluate('Promise.all([document.fonts.ready, ...document.getAnimations().map(animation => animation.finished.catch(() => {}))]).then(() => true)');
    assert.equal(await browser.evaluate('document.documentElement.scrollWidth <= innerWidth'), true, `${width}px has no page overflow`);
    assert.equal(await browser.evaluate("(() => {const panel=document.querySelector('[data-dialog-scroll=api]');return panel.scrollWidth<=panel.clientWidth;})()"), true, `${width}px keeps the code inside its own scroll region`);
    await browser.screenshot(join(screenshots, `api-access-${width}.png`));
  }
  await browser.click('[aria-label="Revoke Read-only browser client"]');
  await browser.until("document.querySelector('#settings-panel-api')?.innerText.includes('No access tokens yet.')", 'Revocation updates the list');
  assert.equal((await fetch(`${origin}/api/catalog`, { headers: { Authorization: `Bearer ${token}` } })).status, 401);
  assert.deepEqual(browser.errors, []);
});
