import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { createServer, type Server } from 'node:http';
import { once } from 'node:events';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { setTimeout as delay } from 'node:timers/promises';
import type { AddressInfo } from 'node:net';
import { Store } from '../../apps/server/store.ts';
import { Engine } from '../../apps/server/engine.ts';
import { ModelLibrary } from '../../apps/server/models.ts';
import type { RuntimeSetupStatus } from '../../apps/server/runtime.ts';
import { createStudioServer } from '../../apps/server/http.ts';
import { dualR9700 } from '../hardware/fixtures.ts';
import { completed, fakeComfy } from '../inference/fake-comfy.ts';
import { openBrowser } from './helpers.ts';

const root = fileURLToPath(new URL('../../', import.meta.url));
const studio = join(root, 'apps/studio');
const close = (server: Server) => new Promise<void>(resolve => { server.closeAllConnections(); server.close(() => resolve()); });
async function freePort() { const server = createServer(); server.listen(0, '127.0.0.1'); await once(server, 'listening'); const port = (server.address() as AddressInfo).port; await close(server); return port; }

test('first run selects GPUs, downloads a checkpoint, generates and restores images through the real Studio API', { timeout: 180000 }, async t => {
  const directory = await mkdtemp(join(tmpdir(), 'gravity-studio-browser-'));
  const output = join(root, '.local/screenshots'); await mkdir(output, { recursive: true });
  const store = new Store(directory);
  const inventory = dualR9700();
  inventory.gpus = inventory.gpus.map((gpu, index) => ({ ...gpu, name: 'AMD Radeon AI PRO R9700', pciAddress: index ? '0000:07:00.0' : '0000:03:00.0' }));
  const engine = new Engine(store, { detect: async () => ({ ...inventory, detectedAt: new Date().toISOString() }), pollMs: 100 });
  const comfy = await fakeComfy();
  const require = createRequire(new URL('../../apps/server/package.json', import.meta.url));
  const sharp = require('sharp') as (input: Buffer) => { png(): { toBuffer(): Promise<Buffer> } };
  comfy.state.outputBytes = Uint8Array.from(await sharp(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="768" height="1024"><rect width="768" height="1024" fill="#24323b"/><rect x="70" y="80" width="628" height="864" rx="4" fill="#344b4c"/><text x="384" y="488" text-anchor="middle" font-family="sans-serif" font-size="26" fill="#d1fe17">COMFYUI PROTOCOL FIXTURE</text><text x="384" y="535" text-anchor="middle" font-family="sans-serif" font-size="18" fill="#e8edeb">Browser integration test · no model inference</text></svg>')).png().toBuffer());
  const completion = setInterval(() => {
    const pending = comfy.state.pending.splice(0);
    for (const prompt of pending) comfy.state.history[String(prompt[1])] = completed(prompt);
  }, 150);
  const frontendPort = await freePort();
  const origin = `http://127.0.0.1:${frontendPort}`;
  let runtimeState: RuntimeSetupStatus = { phase: 'idle', busy: false, message: '', error: null, engine: null, workerCount: 0, updatedAt: null };
  let chosenGpuIds: string[] = [];
  let runtimeOperation: Promise<void> | undefined;
  // Only container execution and the Hugging Face response are fixtures; the owner API,
  // model download, validation, activation, settings and generation use their real code.
  const runtime = {
    status: () => structuredClone(runtimeState),
    start: (body: Record<string, unknown>) => {
      chosenGpuIds = body.gpuIds as string[];
      runtimeState = { ...runtimeState, phase: 'building', busy: true, message: 'Preparing the image engine…' };
      runtimeOperation = delay(750).then(async () => {
        const settings = store.settings();
        settings.workers = [{ id: 'browser-comfy', name: 'GPU 2', baseUrl: comfy.url, enabled: true, deviceIds: chosenGpuIds, location: 'local', maxConcurrentJobs: 1 }];
        store.saveSettings(settings);
        await mkdir(join(directory, 'runtime'), { recursive: true });
        await writeFile(join(directory, 'runtime/plan.json'), JSON.stringify({ workers: settings.workers }));
        runtimeState = { ...runtimeState, phase: 'ready', busy: false, engine: 'podman', workerCount: 1, message: 'Ready', updatedAt: new Date().toISOString() };
      });
      return structuredClone(runtimeState);
    },
    close: async () => { await runtimeOperation; },
  };
  const checkpointUrl = 'https://huggingface.co/gravity-fixtures/browser/blob/main/checkpoint.safetensors';
  const source = checkpointUrl.replace('/blob/', '/resolve/');
  const modelId = `hf-${createHash('sha256').update(source).digest('hex').slice(0, 16)}`;
  const filename = `${modelId}/checkpoint.safetensors`;
  comfy.state.info.CheckpointLoaderSimple.input!.required!.ckpt_name = [[filename]];
  comfy.state.responseOverride = path => path === '/models/checkpoints' ? { body: JSON.stringify([filename]) } : undefined;
  const header = Buffer.from(JSON.stringify({ fixture: { dtype: 'F32', shape: [1], data_offsets: [0, 4] } }));
  const prefix = Buffer.alloc(8); prefix.writeBigUInt64LE(BigInt(header.length));
  const fixtureCheckpoint = Buffer.concat([prefix, header, Buffer.alloc(4)]);
  const models = new ModelLibrary(store, engine, { fetch: async input => {
    assert.equal(String(input), source); await delay(900);
    return new Response(fixtureCheckpoint, { headers: { 'Content-Length': String(fixtureCheckpoint.length) } });
  } });
  const server = await createStudioServer({ store, engine, runtime, models, allowedOrigins: [origin], setupSecret: 'browser-integration-setup-key' });
  server.listen(0, '127.0.0.1'); await once(server, 'listening');
  const backend = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  await engine.start();
  const child = spawn(process.execPath, [join(studio, 'node_modules/next/dist/bin/next'), 'start', '--hostname', '127.0.0.1', '--port', String(frontendPort)], { cwd: studio, env: { ...process.env, GRAVITY_SERVER_URL: backend }, stdio: ['ignore', 'pipe', 'pipe'] });
  let logs = ''; child.stdout.on('data', chunk => { logs = (logs + chunk.toString()).slice(-8000); }); child.stderr.on('data', chunk => { logs = (logs + chunk.toString()).slice(-8000); });
  t.after(async () => { clearInterval(completion); child.kill('SIGTERM'); await delay(200); if (child.exitCode === null) child.kill('SIGKILL'); await server.closeOperations(); await engine.stop(); await close(server); await comfy.close(); store.close(); await rm(directory, { recursive: true, force: true }); });
  for (let attempt = 0; attempt < 100; attempt++) { try { if ((await fetch(`${origin}/api/health`)).ok) break; } catch { /* Starting. */ } if (child.exitCode !== null) throw new Error(`Next could not start: ${logs}`); if (attempt === 99) throw new Error(`Next startup timed out: ${logs}`); await delay(100); }
  const browser = await openBrowser(t);
  async function clickDialogText(id: string, label: string) {
    const element = `Array.from(document.querySelectorAll('#${id} button, #${id} a')).find(element => element.textContent.trim() === ${JSON.stringify(label)})`;
    await browser.until(`!!(${element})`, `${label} in ${id}`);
    const point = await browser.evaluate<{ x: number; y: number }>(`(() => { const element = (${element}); element.scrollIntoView({block: 'nearest'}); const rect = element.getBoundingClientRect(); return {x: rect.left + rect.width / 2, y: rect.top + rect.height / 2}; })()`);
    await browser.send('Input.dispatchMouseEvent', { type: 'mousePressed', ...point, button: 'left', clickCount: 1 });
    await browser.send('Input.dispatchMouseEvent', { type: 'mouseReleased', ...point, button: 'left', clickCount: 1 });
  }
  async function openAdvanced() {
    await browser.click('button[aria-label="Advanced settings"]');
    await browser.until("(() => { const panel = document.querySelector('[aria-label=\"Advanced settings\"]:popover-open'); return panel && getComputedStyle(panel).visibility === 'visible'; })()", 'Advanced settings opens');
  }
  async function screenshotPopover(name: string) {
    await browser.evaluate("Promise.all([document.fonts.ready, ...document.querySelector('[popover]:popover-open').getAnimations().map(animation => animation.finished.catch(() => {}))]).then(() => true)");
    await browser.screenshot(join(output, name));
  }
  async function uploadReference() {
    const file = join(directory, 'reference-upload.png');
    await writeFile(file, comfy.state.outputBytes);
    await browser.send('Page.setInterceptFileChooserDialog', { enabled: true });
    try {
      await browser.click('button[aria-label="Add reference image"]');
      const document = await browser.send('DOM.getDocument') as unknown as { root: { nodeId: number } };
      const input = await browser.send('DOM.querySelector', { nodeId: document.root.nodeId, selector: 'input[aria-label="Upload reference images"]' }) as unknown as { nodeId: number };
      assert.ok(input.nodeId, 'Reference upload uses a native file input');
      await browser.send('DOM.setFileInputFiles', { nodeId: input.nodeId, files: [file] });
      await browser.until("!!document.querySelector('button[aria-label=\"Remove reference 1\"]')", 'Device reference upload finishes');
    } finally { await browser.send('Page.setInterceptFileChooserDialog', { enabled: false }); }
  }
  await browser.navigate(`${origin}/image`);
  await browser.until("document.body.innerText.includes('Make this studio yours.')", 'Owner setup');
  await browser.fill('input[autocomplete="off"]', 'browser-integration-setup-key');
  await browser.fill('input[name="username"]', 'browser-owner');
  await browser.fill('input[name="password"]', 'test-password-strong-123');
  await browser.clickText('Create studio');
  await browser.until("document.querySelector('#settings-dialog[open]')?.innerText.includes('Set up your studio') && document.querySelectorAll('input[name=runtime-gpu]').length === 2", 'GPU onboarding dialog');
  await browser.evaluate("Promise.all(document.querySelector('#settings-dialog').getAnimations().map(animation => animation.finished.catch(() => {})))");
  assert.equal(await browser.evaluate("document.querySelector('#settings-dialog').matches(':modal') && !!document.querySelector('#image-prompt')"), true, 'Onboarding overlays the mounted Image workspace');
  assert.equal(await browser.evaluate("document.querySelectorAll('input[name=runtime-gpu]:checked').length"), 2, 'Detected GPUs are selected by default');
  assert.equal(await browser.evaluate("document.body.innerText.includes('0000:03:00.0') && document.body.innerText.includes('0000:07:00.0')"), true, 'Identical GPUs have visible PCI identities');
  assert.equal(await browser.evaluate("document.body.innerText.includes('Image models') || document.body.innerText.includes('pnpm runtime') || document.body.innerText.includes('GPU used by this worker')"), false, 'Onboarding exposes no terminal commands, worker mapping or model form');
  await browser.screenshot(join(output, 'setup-desktop.png'));
  await browser.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  await browser.until('document.documentElement.clientWidth === 390', 'Mobile onboarding');
  assert.equal(await browser.evaluate('document.documentElement.scrollWidth <= document.documentElement.clientWidth'), true);
  await browser.screenshot(join(output, 'setup-mobile.png'));
  await browser.send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 960, deviceScaleFactor: 1, mobile: false });
  await browser.click('input[name="runtime-gpu"][value="amd:9700a"]');
  await clickDialogText('settings-dialog', 'Set up generation');
  await browser.until("document.body.innerText.includes('Setting up…')", 'Automatic generation setup starts');
  await browser.until("document.body.innerText.includes('Generation is ready')", 'Automatic generation setup finishes');
  assert.deepEqual(chosenGpuIds, ['amd:9700b']);
  assert.deepEqual(store.settings().workers[0].deviceIds, ['amd:9700b']);
  assert.equal(store.settings().modelConfigurations.some(item => item.enabled), false, 'Setup does not choose models');
  await browser.clickText('Start creating');
  await browser.until("!document.querySelector('#settings-dialog[open]') && !!document.querySelector('#image-prompt')", 'Image composer after onboarding closes');
  await browser.clickText('Browse models');
  await browser.until("document.querySelector('#models-dialog[open]')?.innerText.includes('Add from Hugging Face')", 'Model library dialog');
  assert.equal(await browser.evaluate("document.querySelector('#models-dialog').matches(':modal') && location.pathname === '/image'"), true, 'Gallery opens Models without navigating away');
  await browser.fill('input[name="checkpoint-url"]', checkpointUrl);
  await browser.fill('input[name="checkpoint-name"]', 'Browser checkpoint');
  await browser.clickText('Download checkpoint');
  await browser.until("document.body.innerText.includes('Browser checkpoint') && !!document.querySelector('progress')", 'Download progress');
  await browser.click('button[aria-label="Close models"]');
  await browser.until("!document.querySelector('#models-dialog[open]')", 'Download continues after closing Models');
  await browser.until("!!document.querySelector('main button[aria-label=\"Model: Browser checkpoint\"]')", 'Background download refreshes the Image model selection');
  assert.equal(store.settings().modelConfigurations.find(item => item.modelId === modelId)?.enabled, true);
  assert.deepEqual(store.settings().modelConfigurations.find(item => item.modelId === modelId)?.workerIds, ['browser-comfy']);
  await browser.click('header button[aria-label="Models"]');
  await browser.until("document.querySelector('#models-dialog[open]')?.innerText.includes('Ready to use')", 'Downloaded checkpoint is activated when Models reopens');
  await browser.evaluate("document.querySelectorAll('#models-dialog, #models-dialog *').forEach(element => { if (getComputedStyle(element).overflowY === 'auto') element.scrollTop = 0; })");
  await browser.screenshot(join(output, 'models-desktop.png'));
  await browser.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  assert.equal(await browser.evaluate('document.documentElement.scrollWidth <= document.documentElement.clientWidth'), true);
  await browser.screenshot(join(output, 'models-mobile.png'));
  await browser.send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 960, deviceScaleFactor: 1, mobile: false });
  await browser.click('button[aria-label="Close models"]');
  await browser.until("!document.querySelector('#models-dialog[open]')", 'Model library closes after import');
  await browser.until("!!document.querySelector('button[aria-label=\"Model: Browser checkpoint\"]')", 'Ready model');
  const prompt = 'A cinematic forest in the morning mist';
  await browser.fill('#image-prompt', prompt);
  const advertised = await browser.evaluate<{ defaults: { width: number; height: number; steps: number; cfg: number }; dimensions: { multiple: number; min: number; max: number; maxPixels: number }; capabilities: { negativePrompt: boolean } }>(`fetch('/api/catalog').then(response => response.json()).then(catalog => catalog.models.find(model => model.id === ${JSON.stringify(modelId)}))`);
  assert.equal(await browser.evaluate("document.querySelector('button[aria-label=\"Reset settings to defaults\"]').disabled"), true, 'Reset is disabled when generation settings match the selected model');
  assert.equal(await browser.evaluate("Array.from(document.querySelectorAll('main button')).some(button => /^\\d+ steps$/.test(button.textContent.trim()))"), false, 'Sampling steps live in Advanced rather than a separate toolbar chip');
  await browser.click('button[aria-label="Model: Browser checkpoint"]');
  await browser.until("!!document.querySelector('[popover]:popover-open [role=menuitem][aria-current=true]')", 'Selected model row');
  assert.equal(await browser.evaluate("!!document.querySelector('[popover]:popover-open input[aria-label=\"Search models\"]')"), false, 'A short model list needs no search field');
  assert.equal(await browser.evaluate("Array.from(document.querySelectorAll('[popover]:popover-open [role=menuitem]')).find(row => row.textContent.includes('SDXL Base 1.0'))?.disabled"), true, 'A model without installed files cannot be selected');
  await browser.click('button[aria-label="Manage image models"]');
  await browser.until("!!document.querySelector('#models-dialog[open]') && !document.querySelector('[popover]:popover-open')", 'Model menu opens its management modal');
  await browser.click('button[aria-label="Close models"]');
  assert.equal(await browser.evaluate("document.querySelector('#image-prompt').value"), prompt, 'Managing models preserves the prompt');
  await browser.click('button[aria-label^="Aspect ratio:"]');
  await browser.until("!!document.querySelector('[popover]:popover-open [aria-label=\"Aspect ratio 16:9\"]')", 'Aspect ratio menu');
  await screenshotPopover('ratios-desktop.png');
  await browser.click('[popover]:popover-open [aria-label="Aspect ratio 16:9"]');
  await browser.until("!!document.querySelector('button[aria-label=\"Aspect ratio: 16:9\"]') && !document.querySelector('[popover]:popover-open')", 'Pointer chooses a widescreen aspect');
  await openAdvanced();
  const widescreen = await browser.evaluate<{ width: number; height: number }>("({width: Number(document.querySelector('input[aria-label=\"Width value\"]').value), height: Number(document.querySelector('input[aria-label=\"Height value\"]').value)})");
  assert.ok(widescreen.width > widescreen.height && Math.abs(widescreen.width / widescreen.height - 16 / 9) < .06, 'Widescreen dimensions approximate the requested ratio');
  for (const side of [widescreen.width, widescreen.height]) assert.ok(side >= advertised.dimensions.min && side <= advertised.dimensions.max && side % advertised.dimensions.multiple === 0);
  assert.ok(widescreen.width * widescreen.height <= advertised.dimensions.maxPixels, 'Aspect choices stay within the advertised pixel budget');
  assert.equal(await browser.evaluate("!!document.querySelector('[popover]:popover-open input[aria-label=\"Image strength value\"]')"), false, 'Text-to-image has no image-strength control');
  await browser.key('Escape');
  await browser.click('button[aria-label^="Aspect ratio:"]');
  await browser.until("document.activeElement?.getAttribute('role') === 'menuitem' && !!document.activeElement.closest('[popover]:popover-open')", 'Aspect menu receives keyboard focus');
  await browser.key('Home');
  assert.equal(await browser.evaluate('document.activeElement?.getAttribute("aria-label")'), 'Aspect ratio Auto', 'Home focuses the first aspect choice');
  await browser.key('Enter');
  await browser.until("!!document.querySelector('button[aria-label=\"Aspect ratio: Auto\"]') && !document.querySelector('[popover]:popover-open')", 'Keyboard chooses the default aspect');
  await openAdvanced();
  assert.deepEqual(await browser.evaluate("({width: Number(document.querySelector('input[aria-label=\"Width value\"]').value), height: Number(document.querySelector('input[aria-label=\"Height value\"]').value)})"), { width: advertised.defaults.width, height: advertised.defaults.height });
  await browser.fill('input[aria-label="Steps value"]', '24');
  assert.equal(await browser.evaluate("document.querySelector('input[type=range][aria-label=Steps]').value"), '24', 'Steps number field updates its slider');
  await browser.fill('input[type="range"][aria-label="Guidance"]', '6.5');
  assert.equal(await browser.evaluate("document.querySelector('input[aria-label=\"Guidance value\"]').value"), '6.5', 'Guidance slider updates its number field');
  await browser.evaluate("document.querySelector('input[type=range][aria-label=Width]').focus()");
  assert.equal(await browser.evaluate('document.activeElement?.getAttribute("aria-label")'), 'Width', 'Width slider receives keyboard focus');
  await browser.key('ArrowRight');
  const generationWidth = advertised.defaults.width + advertised.dimensions.multiple;
  assert.equal(await browser.evaluate("Number(document.querySelector('input[aria-label=\"Width value\"]').value)"), generationWidth, 'Keyboard slider changes width by the model grid');
  await browser.fill('input[aria-label="Height value"]', '768');
  assert.equal(await browser.evaluate("document.querySelector('input[type=range][aria-label=Height]').value"), '768', 'Height number field updates its slider');
  await browser.fill('input[aria-label="Seed"]', '1234');
  await browser.click('button[aria-label="Randomise seed"]');
  const randomized = await browser.evaluate<string>("document.querySelector('input[aria-label=Seed]').value");
  assert.ok(/^\d+$/.test(randomized) && Number(randomized) >= 0 && Number(randomized) <= 0xffffffff && randomized !== '1234', 'Shuffle sets a fresh valid seed');
  await browser.fill('input[aria-label="Seed"]', '1234');
  assert.equal(advertised.capabilities.negativePrompt, true);
  await browser.fill('[popover]:popover-open textarea', 'text, watermark');
  await browser.evaluate("document.querySelectorAll('[popover]:popover-open *').forEach(element => { if (getComputedStyle(element).overflowY === 'auto') element.scrollTop = 0; })");
  await screenshotPopover('advanced-desktop.png');
  await browser.key('Escape');
  await browser.until("!document.querySelector('[popover]:popover-open')", 'Escape dismisses advanced');
  assert.equal(await browser.evaluate('document.activeElement?.getAttribute("aria-label")'), 'Advanced settings');
  await browser.clickText('Generate');
  await browser.until("!!document.querySelector('button[aria-label=\"Open Browser checkpoint output\"]')", 'Generated output in gallery');
  const first = store.jobs(store.owner()!.id)[0];
  assert.equal(first.status, 'succeeded'); assert.equal(first.parameters.seed, 1234); assert.equal(comfy.state.submissions.length, 1);
  assert.deepEqual({ width: first.parameters.width, height: first.parameters.height, steps: first.parameters.steps, cfg: first.parameters.cfg, negativePrompt: first.parameters.negativePrompt }, { width: generationWidth, height: 768, steps: 24, cfg: 6.5, negativePrompt: 'text, watermark' }, 'Generation uses the edited toolbar parameters');
  await browser.until("Array.from(document.querySelectorAll('figure img')).every(image => image.complete && image.naturalWidth > 0)", 'Output image pixels loaded');
  await browser.screenshot(join(output, 'image-desktop.png'));
  await browser.fill('#image-prompt', 'Temporary draft');
  await browser.click('[aria-label="Use these settings"]');
  await browser.until(`document.querySelector('#image-prompt').value === ${JSON.stringify(prompt)}`, 'Restore accepted prompt');
  await uploadReference();
  assert.equal(await browser.evaluate("document.querySelector('input[aria-label=\"Upload reference images\"]').disabled && !document.querySelector('button[aria-label=\"Add reference image\"]')"), true, 'The single-reference model prevents a second upload');
  await browser.fill('#image-prompt', 'Keep the composition and turn morning into twilight');
  await openAdvanced();
  await browser.fill('input[aria-label="Image strength value"]', '.45');
  assert.equal(await browser.evaluate("document.querySelector('input[type=range][aria-label=\"Image strength\"]').value"), '0.45', 'Image strength stays synchronized with its slider');
  await browser.key('Escape');
  await browser.evaluate("void (window.__gravityResetReference = document.querySelector('button[aria-label=\"Remove reference 1\"]'))");
  await browser.click('button[aria-label="Reset settings to defaults"]');
  assert.equal(await browser.evaluate("document.querySelector('#image-prompt').value"), 'Keep the composition and turn morning into twilight', 'Reset preserves the prompt');
  assert.equal(await browser.evaluate("document.querySelector('button[aria-label=\"Remove reference 1\"]') === window.__gravityResetReference"), true, 'Reset preserves the selected reference');
  assert.equal(await browser.evaluate("document.querySelector('button[aria-label=\"Reset settings to defaults\"]').disabled"), true, 'Reset becomes disabled after restoring defaults');
  await openAdvanced();
  const resetValues = await browser.evaluate("({ width: Number(document.querySelector('input[aria-label=\"Width value\"]').value), height: Number(document.querySelector('input[aria-label=\"Height value\"]').value), steps: Number(document.querySelector('input[aria-label=\"Steps value\"]').value), cfg: Number(document.querySelector('input[aria-label=\"Guidance value\"]').value), seed: document.querySelector('input[aria-label=Seed]').value, negativePrompt: document.querySelector('[popover]:popover-open textarea').value, denoise: Number(document.querySelector('input[aria-label=\"Image strength value\"]').value) })");
  assert.deepEqual(resetValues, { width: advertised.defaults.width, height: advertised.defaults.height, steps: advertised.defaults.steps, cfg: advertised.defaults.cfg, seed: '', negativePrompt: '', denoise: .75 });
  await browser.fill('input[aria-label="Width value"]', '2048');
  assert.ok(await browser.evaluate<number>("Number(document.querySelector('input[type=range][aria-label=Height]').max)") * 2048 <= advertised.dimensions.maxPixels, 'Slider maximum respects the shared pixel budget');
  await browser.fill('input[aria-label="Height value"]', '2048');
  await browser.until("document.querySelector('main [role=alert]')?.textContent.includes('pixels')", 'An oversized typed image receives a visible explanation');
  assert.equal(await browser.evaluate("Array.from(document.querySelectorAll('main button')).find(button => button.textContent.trim() === 'Generate').disabled"), true, 'Generation is blocked for a manually entered size above the pixel budget');
  await browser.key('Escape');
  await browser.click('button[aria-label="Reset settings to defaults"]');
  await browser.until("!document.querySelector('main [role=alert]') && !Array.from(document.querySelectorAll('main button')).find(button => button.textContent.trim() === 'Generate').disabled", 'Reset restores a valid, generatable image size');
  assert.equal(await browser.evaluate("document.querySelector('button[aria-label=\"Remove reference 1\"]') === window.__gravityResetReference"), true, 'Recovery from invalid dimensions keeps the reference');
  await browser.click('button[aria-label="Remove reference 1"]');
  await browser.until("!!document.querySelector('button[aria-label=\"Browse saved images\"]')", 'Removing a reference makes upload and saved-image selection available');
  await browser.click('[aria-label="Browse saved images"]');
  await browser.until("!!document.querySelector('dialog[open]')", 'Reference picker opens');
  await browser.click('dialog button[aria-label^="Use reference:"]');
  await browser.until("!document.querySelector('dialog[open]') && !!document.querySelector('button[aria-label=\"Remove reference 1\"]')", 'Reference is uploaded');
  await browser.fill('#image-prompt', 'Keep the composition and turn morning into twilight');
  await browser.clickText('Generate');
  await browser.until("document.querySelectorAll('button[aria-label=\"Open Browser checkpoint output\"]').length === 2", 'Reference generation completes');
  assert.equal(store.jobs(store.owner()!.id)[0].input.operation, 'image-to-image');
  assert.ok(comfy.state.uploadBody.includes('filename='));
  await browser.send('Page.reload');
  await browser.until("document.querySelectorAll('button[aria-label=\"Open Browser checkpoint output\"]').length === 2", 'Durable gallery after reload');
  await browser.until("document.querySelector('#image-prompt')?.value.includes('twilight') && !!document.querySelector('button[aria-label=\"Remove reference 1\"]')", 'Draft and references persist after reload');
  await browser.click('[aria-label="Open Browser checkpoint output"]');
  await browser.until("!!document.querySelector('dialog[open]')", 'Output viewer opens');
  await browser.key('Escape');
  await browser.until("!document.querySelector('dialog[open]')", 'Output viewer Escape closes');

  // Keep a genuine scrolled gallery and a live draft beneath both overlays.
  // DOM identity catches remounts that restoring localStorage alone would conceal.
  const modalDraft = 'Keep this unfinished prompt while browsing my models and settings';
  await browser.fill('#image-prompt', modalDraft);
  await browser.fill('input[aria-label="Image tile size"]', '1');
  async function checkWorkspaceModal(label: 'Models' | 'Settings', closeWith: 'escape' | 'backdrop', viewport: string) {
    const id = `${label.toLowerCase()}-dialog`;
    const trigger = `header button[aria-label="${label}"]`;
    const findGallery = "(() => { let element = document.querySelector('figure'); while (element && element !== document.body) { if (['auto', 'scroll'].includes(getComputedStyle(element).overflowY) && element.scrollHeight > element.clientHeight) return element; element = element.parentElement; } return null; })()";
    await browser.until(`!!(${findGallery})`, `${viewport} gallery has actual overflow`);
    await browser.evaluate(`(() => { const gallery = (${findGallery}); gallery.scrollTop = Math.min(120, gallery.scrollHeight - gallery.clientHeight); window.__gravityModalState = { prompt: document.querySelector('#image-prompt'), value: document.querySelector('#image-prompt').value, gallery, scrollTop: gallery.scrollTop, trigger: document.querySelector(${JSON.stringify(trigger)}), reference: document.querySelector('button[aria-label="Remove reference 1"]') }; })()`);
    assert.equal(await browser.evaluate('window.__gravityModalState.scrollTop > 0'), true, 'The preservation check uses a nonzero scroll position');
    const workspaceWidth = await browser.evaluate<number>("document.querySelector('main').getBoundingClientRect().width");
    assert.equal(await browser.evaluate('document.querySelector("main").getBoundingClientRect().width >= innerWidth - 2'), true, 'Image workspace uses the full viewport width');
    await browser.click(trigger);
    await browser.until(`document.querySelector('#${id}[open]')?.matches(':modal')`, `${label} opens as a native modal`);
    await browser.until(`Array.from(document.querySelectorAll('#${id} h1, #${id} h2')).some(heading => heading.textContent.trim() === ${JSON.stringify(label)})`, `${label} modal heading`);
    await browser.evaluate(`Promise.all(document.querySelector('#${id}').getAnimations().map(animation => animation.finished.catch(() => {})))`);
    assert.equal(await browser.evaluate(`(() => { const dialog = document.querySelector('#${id}'); const rect = dialog.getBoundingClientRect(); return rect.left >= 0 && rect.top >= 0 && rect.right <= innerWidth + 1 && rect.bottom <= innerHeight + 1 && dialog.scrollWidth <= dialog.clientWidth + 1; })()`), true, `${viewport} ${label} fits the viewport without horizontal overflow`);
    assert.equal(await browser.evaluate<number>("document.querySelector('main').getBoundingClientRect().width"), workspaceWidth, 'Opening an overlay does not narrow the Image workspace');
    assert.equal(await browser.evaluate("document.querySelector('#image-prompt') === window.__gravityModalState.prompt && window.__gravityModalState.gallery.isConnected"), true, 'Composer and gallery remain mounted behind the dialog');
    assert.equal(await browser.evaluate<string>("document.querySelector('#image-prompt').value"), modalDraft);
    const focusables = `Array.from(document.querySelectorAll('#${id} button, #${id} a[href], #${id} input, #${id} select, #${id} textarea, #${id} summary, #${id} [tabindex]')).filter(element => !element.disabled && element.tabIndex >= 0 && element.getClientRects().length && getComputedStyle(element).visibility === 'visible')`;
    await browser.evaluate(`(${focusables}).at(-1).focus()`);
    await browser.key('Tab');
    assert.equal(await browser.evaluate(`document.querySelector('#${id}').contains(document.activeElement)`), true, `Tab stays inside the modal; focused ${await browser.evaluate('document.activeElement?.outerHTML.slice(0, 200)')}`);
    await browser.evaluate(`(${focusables})[0].focus()`);
    await browser.send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Tab', code: 'Tab', windowsVirtualKeyCode: 9, modifiers: 1 });
    await browser.send('Input.dispatchKeyEvent', { type: 'keyUp', key: 'Tab', code: 'Tab', windowsVirtualKeyCode: 9, modifiers: 1 });
    assert.equal(await browser.evaluate(`document.querySelector('#${id}').contains(document.activeElement)`), true, 'Shift+Tab stays inside the modal');
    await browser.evaluate("document.querySelector('#image-prompt').focus()");
    assert.equal(await browser.evaluate(`document.querySelector('#${id}').contains(document.activeElement)`), true, 'The underlying composer is inert while the dialog is open');
    await browser.screenshot(join(output, `${label.toLowerCase()}-modal-${viewport}.png`));
    if (closeWith === 'escape') await browser.key('Escape');
    else {
      const point = await browser.evaluate<{ x: number; y: number } | null>(`(() => { const rect = document.querySelector('#${id}').getBoundingClientRect(); return [{x: 2, y: 2}, {x: innerWidth - 2, y: 2}, {x: 2, y: innerHeight - 2}, {x: innerWidth - 2, y: innerHeight - 2}].find(point => point.x < rect.left || point.x > rect.right || point.y < rect.top || point.y > rect.bottom) || null; })()`);
      assert.ok(point, 'The modal leaves a clickable backdrop');
      await browser.send('Input.dispatchMouseEvent', { type: 'mousePressed', ...point, button: 'left', clickCount: 1 });
      await browser.send('Input.dispatchMouseEvent', { type: 'mouseReleased', ...point, button: 'left', clickCount: 1 });
    }
    await browser.until(`!document.querySelector('#${id}[open]')`, `${label} closes by ${closeWith}`);
    assert.equal(await browser.evaluate('document.activeElement === window.__gravityModalState.trigger'), true, 'Focus returns to the opener');
    assert.equal(await browser.evaluate("document.querySelector('#image-prompt') === window.__gravityModalState.prompt && document.querySelector('#image-prompt').value === window.__gravityModalState.value"), true, 'The same composer retains the unfinished draft');
    assert.equal(await browser.evaluate('window.__gravityModalState.gallery.isConnected && window.__gravityModalState.gallery.scrollTop === window.__gravityModalState.scrollTop'), true, 'The same gallery retains its scroll position');
    assert.equal(await browser.evaluate("document.querySelector('button[aria-label=\"Remove reference 1\"]') === window.__gravityModalState.reference"), true, 'Selected reference remains mounted');
    assert.equal(await browser.evaluate('location.pathname'), '/image', 'Opening and closing dialogs does not navigate away');
  }
  await browser.send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 700, deviceScaleFactor: 1, mobile: false });
  await checkWorkspaceModal('Models', 'escape', 'desktop');
  await checkWorkspaceModal('Settings', 'backdrop', 'desktop');
  await browser.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  await browser.until('document.documentElement.clientWidth === 390', 'Mobile viewport');
  await checkWorkspaceModal('Models', 'backdrop', 'mobile');
  await checkWorkspaceModal('Settings', 'escape', 'mobile');
  await browser.click('button[aria-label="Remove reference 1"]');
  await browser.until("!!document.querySelector('button[aria-label=\"Add reference image\"]')", 'Mobile upload control is available after removing a reference');
  for (const label of ['Add reference image', 'Browse saved images']) {
    assert.equal(await browser.evaluate(`(() => { const rect = document.querySelector('button[aria-label=${JSON.stringify(label)}]').getBoundingClientRect(); return rect.width >= 40 && rect.height >= 40 && rect.left >= 0 && rect.right <= innerWidth && rect.top >= 0 && rect.bottom <= innerHeight; })()`), true, `${label} remains reachable on mobile`);
  }
  await uploadReference();
  assert.equal(await browser.evaluate("document.querySelector('#image-prompt').value"), modalDraft, 'Mobile upload preserves the unfinished prompt');
  await browser.click('button[aria-label^="Aspect ratio:"]');
  await browser.until("!!document.querySelector('[popover]:popover-open [aria-label=\"Aspect ratio 3:4\"]')", 'Mobile aspect menu');
  assert.equal(await browser.evaluate("(() => { const menu = document.querySelector('[popover]:popover-open'); const rect = menu.getBoundingClientRect(); return rect.left >= 0 && rect.right <= innerWidth && rect.top >= 0 && rect.bottom <= innerHeight && menu.scrollWidth <= menu.clientWidth; })()"), true, 'Aspect menu fits the mobile viewport');
  await screenshotPopover('ratios-mobile.png');
  await browser.click('[popover]:popover-open [aria-label="Aspect ratio 3:4"]');
  await openAdvanced();
  assert.equal(await browser.evaluate("(() => { const menu = document.querySelector('[aria-label=\"Advanced settings\"]:popover-open'); const rect = menu.getBoundingClientRect(); return rect.left >= 0 && rect.right <= innerWidth && rect.top >= 0 && rect.bottom <= innerHeight && menu.scrollWidth <= menu.clientWidth; })()"), true, 'Advanced controls fit the mobile viewport');
  assert.equal(await browser.evaluate("Number(document.querySelector('input[aria-label=\"Height value\"]').value) > Number(document.querySelector('input[aria-label=\"Width value\"]').value)"), true, 'Mobile portrait choice updates dimensions');
  await screenshotPopover('advanced-mobile.png');
  await browser.key('Escape');
  await browser.click('button[aria-label="Reset settings to defaults"]');
  assert.equal(await browser.evaluate("!!document.querySelector('button[aria-label=\"Remove reference 1\"]') && document.querySelector('#image-prompt').value === window.__gravityModalState.value"), true, 'Mobile reset keeps the uploaded reference and prompt');
  assert.equal(await browser.evaluate('document.documentElement.scrollWidth <= document.documentElement.clientWidth'), true, 'Mobile page must not overflow horizontally');
  assert.equal(await browser.evaluate("(() => { const button = Array.from(document.querySelectorAll('button')).find(button => button.textContent.trim() === 'Generate'); const rect = button.getBoundingClientRect(); return rect.width >= 44 && rect.height >= 44 && rect.bottom <= innerHeight; })()"), true, 'Generate remains reachable on mobile');
  await browser.until("(() => { const input = document.querySelector('#image-prompt'); return input.scrollHeight <= input.clientHeight + 2; })()", 'Mobile prompt fits its wrapped text');
  await browser.screenshot(join(output, 'image-mobile.png'));
  comfy.state.postBehavior = 'drop-before-accept';
  await browser.clickText('Generate');
  await browser.until("document.body.innerText.includes('Close unknown job')", 'Uncertain generation offers owner resolution');
  const unknown = store.jobs(store.owner()!.id)[0];
  assert.equal(unknown.status, 'interrupted');
  const declined = browser.answerNextDialog(false);
  await browser.clickText('Close unknown job');
  assert.match(await declined, /recheck.*queue and history/);
  assert.equal(store.job(unknown.id).status, 'interrupted', 'Dismissing confirmation keeps the resource reservation');
  const accepted = browser.answerNextDialog(true);
  await browser.clickText('Close unknown job');
  await accepted;
  await browser.until("document.body.innerText.includes('Closed by owner')", 'Owner closes the absent generation');
  assert.equal(store.job(unknown.id).status, 'failed');
  assert.equal(comfy.state.submissions.filter(item => item.prompt_id === unknown.id).length, 1, 'Closing does not resubmit');
  await browser.click('header button[aria-label="Settings"]');
  await browser.until("document.querySelector('#settings-dialog[open]')?.innerText.includes('GPUs to use')", 'Mobile settings dialog');
  await browser.screenshot(join(output, 'settings-mobile.png'));
  await browser.click('summary');
  await browser.clickText('API access');
  await browser.until("document.body.innerText.includes('API & MCP access')", 'API access settings');
  await browser.fill('input[placeholder="My MCP client"]', 'Browser test MCP');
  await browser.clickText('Create token');
  await browser.until("document.querySelector('input[aria-label=\"New access token\"]')?.value.startsWith('gs_')", 'Access token created');
  const token = await browser.evaluate<string>("document.querySelector('input[aria-label=\"New access token\"]').value");
  const apiResponse = await fetch(`${origin}/api/catalog`, { headers: { Authorization: `Bearer ${token}` } });
  assert.equal(apiResponse.status, 200, 'The token authenticates API requests');
  const mcp = await fetch(`${origin}/api/mcp`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', Accept: 'application/json, text/event-stream', 'MCP-Protocol-Version': '2025-11-25' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-11-25', capabilities: {}, clientInfo: { name: 'browser-integration', version: '1.0.0' } } }) });
  assert.equal(mcp.status, 200, 'The frontend proxy forwards MCP transport headers');
  const mcpText = await mcp.text();
  const mcpResult = JSON.parse(mcp.headers.get('content-type')?.includes('text/event-stream') ? mcpText.split('\n').find(line => line.startsWith('data: '))!.slice(6) : mcpText) as { result: { serverInfo: { name: string } } };
  assert.equal(mcpResult.result.serverInfo.name, 'gravity-studio');
  await browser.clickText('I have saved it');
  await browser.until("!document.querySelector('input[aria-label=\"New access token\"]')", 'Token secret hidden');
  await browser.screenshot(join(output, 'api-mobile.png'));
  await browser.click('[aria-label="Revoke Browser test MCP"]');
  await browser.until("document.body.innerText.includes('No access tokens yet.')", 'Token revoked');
  assert.equal((await fetch(`${origin}/api/catalog`, { headers: { Authorization: `Bearer ${token}` } })).status, 401);
  await browser.click('button[aria-label="Close settings"]');
  await browser.until("!document.querySelector('#settings-dialog[open]')", 'Settings closes before account controls are used');
  await browser.click('[aria-label="Account"]');
  await browser.clickText('Sign out');
  await browser.until("document.body.innerText.includes('Welcome back.')", 'Signed out');
  await browser.fill('input[name="username"]', 'browser-owner');
  await browser.fill('input[name="password"]', 'test-password-strong-123');
  await browser.clickText('Sign in');
  await browser.until("!!document.querySelector('#image-prompt') && !document.querySelector('dialog[open]')", 'Owner signs back into the Image workspace');
  for (const label of ['Models', 'Settings']) {
    await browser.navigate(`${origin}/${label.toLowerCase()}`);
    await browser.until(`!!document.querySelector('#${label.toLowerCase()}-dialog[open]') && !!document.querySelector('#image-prompt')`, `${label} entry URL opens its dialog over Image`);
    await browser.click(`button[aria-label="Close ${label.toLowerCase()}"]`);
    await browser.until("!document.querySelector('dialog[open]') && !!document.querySelector('#image-prompt')", `${label} entry dialog closes to Image`);
  }
  assert.deepEqual(browser.errors, []);
  t.diagnostic(`Screenshots: ${output}`);
});
