'use client';

import { useRef, useState } from 'react';
import type { WorkTimeDetails, WorkTimeUser } from '../../../../../packages/contracts/work-time';
import { api } from '@/lib/api';
import { button, copy, date, duration, Feedback, Heading, Loading, primary, requestKey, useAction, useResource } from './shared';

export function WorkTimePanel() {
  const resource = useResource<{ users: WorkTimeUser[] }>('/admin/work-time', 15_000);
  const [selected, setSelected] = useState(''), [query, setQuery] = useState('');
  const users = resource.data?.users.filter(user => !['deleted', 'deleting'].includes(user.status) && user.username.toLowerCase().includes(query.toLowerCase())) || [];
  const user = users.find(user => user.id === selected) || users[0];
  return <section><Heading title="Work time" onRefresh={resource.reload} loading={resource.loading}>Manage each account’s allowance and review recorded server time.</Heading><Feedback error={resource.error} />{resource.loading && <Loading>Loading balances…</Loading>}
    <div className="grid min-w-0 gap-7 xl:grid-cols-[minmax(230px,300px)_minmax(0,1fr)]"><div className="min-w-0"><label className="field mb-4">Find a user<input aria-label="Search work time users" value={query} onChange={event => setQuery(event.target.value)} /></label><ul className="max-h-[55dvh] overflow-y-auto">{users.map(entry => <li key={entry.id}><button type="button" aria-pressed={user?.id === entry.id} onClick={() => setSelected(entry.id)} className={`flex w-full items-center justify-between gap-3 rounded-lg px-3 py-3 text-left text-sm ${entry.id === user?.id ? 'bg-chip' : 'hover:bg-panel-2'}`}><span className="min-w-0 break-words">{entry.username}</span><span className="shrink-0 text-xs tabular-nums text-ink-2">{entry.balance.unlimited ? 'Unlimited' : duration(entry.balance.remainingMs)}</span></button></li>)}</ul>{!resource.loading && !users.length && <p className={copy}>No users match your search.</p>}</div>
      {user && <TimeDetails key={user.id} path={`/admin/users/${encodeURIComponent(user.id)}/work-time`} title={user.username} editable={!user.balance.unlimited} onChanged={resource.reload} />}
    </div>
  </section>;
}

export function OwnWorkTime({ active = true }: { active?: boolean }) { return <TimeDetails path={active ? '/work-time' : null} title="Your server time" />; }
function TimeDetails({ path, title, editable = false, onChanged }: { path: string | null; title: string; editable?: boolean; onChanged?: () => void }) {
  const resource = useResource<WorkTimeDetails>(path, 15_000), action = useAction();
  const [hours, setHours] = useState('2'), [minutes, setMinutes] = useState('0'), [direction, setDirection] = useState('add'), [reason, setReason] = useState('');
  const attempt = useRef<{ body: string; key: string } | null>(null);
  const balance = resource.data?.balance, amount = (Number(hours) * 60 + Number(minutes)) * 60_000;
  const valid = Number.isInteger(Number(hours)) && Number(hours) >= 0 && Number.isInteger(Number(minutes)) && Number(minutes) >= 0 && Number(minutes) < 60 && amount > 0 && amount <= 31_536_000_000;
  return <div className="min-w-0"><h2 className="text-lg font-medium">{title}</h2><Feedback error={resource.error || action.error} notice={action.notice} />{resource.loading && <Loading>Reading server time…</Loading>}
    {balance && <><dl className="mt-4 divide-y divide-line border-y border-line">{[['Remaining', balance.unlimited ? 'Unlimited' : duration(balance.remainingMs)], ['Used', duration(balance.usedMs)], ['Assigned', balance.unlimited ? 'Unlimited' : duration(balance.grantedMs)], ['Active tasks', String(balance.activeTasks)]].map(([label, value]) => <div key={label} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><dt className="text-ink-2">{label}</dt><dd className="tabular-nums">{value}</dd></div>)}</dl>
      <p className="mt-3 text-xs leading-relaxed text-ink-2">Overlapping tasks count once. Queued jobs and idle models use no time. Started tasks finish; any overrun counts against the next allowance.</p>
      {balance.uncertainTasks > 0 && <p role="status" className="mt-3 text-xs leading-relaxed text-[#ffc3aa]">{balance.uncertainTasks} interrupted task{balance.uncertainTasks === 1 ? '' : 's'} still hold server resources. Their time continues until resolved.</p>}
      <p className="mt-2 text-xs text-ink-2">Updated {date(balance.sampledAt)}{balance.trackedSince ? ` · Tracked since ${date(balance.trackedSince)}` : ''}</p>
    </>}
    {editable && balance && <form className="mt-7 border-t border-line pt-6" onSubmit={event => { event.preventDefault(); if (!valid || !reason.trim()) return; void action.run(async signal => { const body = { deltaMs: direction === 'add' ? amount : -amount, reason: reason.trim() }, signature = JSON.stringify(body); if (attempt.current?.body !== signature) attempt.current = { body: signature, key: requestKey() }; await api(path!, { method: 'POST', body: JSON.stringify({ ...body, idempotencyKey: attempt.current.key }), signal }); attempt.current = null; setReason(''); resource.reload(); onChanged?.(); action.setNotice('Server time adjusted. The change is recorded in the history.'); }); }}><h3 className="text-sm font-medium">Adjust allowance</h3><fieldset disabled={action.busy || !!resource.error} className="mt-4 grid min-w-0 grid-cols-2 gap-4"><label className="field col-span-2">Action<select name="time-direction" value={direction} onChange={event => setDirection(event.target.value)}><option value="add">Add time</option><option value="remove">Remove unused time</option></select></label><label className="field">Hours<input name="time-hours" type="number" min={0} max={8760} step={1} required value={hours} onChange={event => setHours(event.target.value)} /></label><label className="field">Minutes<input name="time-minutes" type="number" min={0} max={59} step={1} required value={minutes} onChange={event => setMinutes(event.target.value)} /></label><label className="field col-span-2">Reason<input name="time-reason" maxLength={240} required value={reason} onChange={event => setReason(event.target.value)} placeholder="Monthly allowance" /></label><div className="col-span-2"><button className={primary} disabled={action.busy || !valid || !reason.trim()}>{action.busy ? 'Saving…' : direction === 'add' ? 'Add server time' : 'Remove unused time'}</button></div></fieldset></form>}
    {resource.data && <div className="mt-7 space-y-5"><details><summary className="cursor-pointer py-2 text-sm font-medium">Server activity</summary><p className="my-2 text-xs text-ink-2">Latest 100 periods of active work.</p><ul className="max-h-72 divide-y divide-line overflow-y-auto">{resource.data.sessions.map(session => <li key={session.id} className="flex flex-wrap justify-between gap-3 py-3 text-xs"><span>{date(session.startedAt)}<span className="mt-1 block text-ink-2">{session.endedAt ? `Finished ${date(session.endedAt)}` : 'In progress'}</span></span><span className="tabular-nums">{duration(session.durationMs)}</span></li>)}</ul>{!resource.data.sessions.length && <p className="py-3 text-xs text-ink-2">No recorded server time yet.</p>}</details><details><summary className="cursor-pointer py-2 text-sm font-medium">Allowance history</summary><ul className="max-h-72 divide-y divide-line overflow-y-auto">{resource.data.adjustments.map(change => <li key={change.id} className="flex flex-wrap justify-between gap-3 py-3 text-xs"><span className="min-w-0 flex-1 break-words">{change.reason}<span className="mt-1 block text-ink-2">{date(change.createdAt)}</span></span><span className="tabular-nums">{change.amountMs > 0 ? '+' : ''}{duration(change.amountMs)}</span></li>)}</ul>{!resource.data.adjustments.length && <p className="py-3 text-xs text-ink-2">No allowance changes yet.</p>}</details></div>}
    {resource.error && <button type="button" className={`${button} mt-3`} onClick={resource.reload}>Try again</button>}
  </div>;
}
